[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
contract = "98TGc38djoRGd7rczpJ2nJWgLv2oNpXrDcGkJ8n4kPDG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/icarus/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
